Fix the custom_gradient issue with hermite_renormalized (#506)
### **User description**
### Before submitting

Please complete the following checklist when submitting a PR:

- [x] All new features must include a unit test.
If you've fixed a bug or added code that should be tested, add a test to
the
      test directory!

- [x] All new functions and code must be clearly commented and
documented.
If you do make documentation changes, make sure that the docs build and
      render correctly by running `make docs`.

- [X] Ensure that the test suite passes, by running `make test`.

- [x] Ensure that code and tests are properly formatted, by running
`make format` or `black -l 100
<filename>` on any relevant files. You will need to have the Black code
format installed:
      `pip install black`.

- [ ] Add a new entry to the `.github/CHANGELOG.md` file, summarizing
the
      change, and including a link back to the PR.

- [x] The Mr Mustard source code conforms to
[PEP8 standards](https://www.python.org/dev/peps/pep-0008/) except line
length.
We check all of our code against [Pylint](https://www.pylint.org/).
      To lint modified files, simply `pip install pylint`, and then
      run `pylint mrmustard/path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.


------------------------------------------------------------------------------------------------------------

**Context:**
This PR fixes the following MM issue with TensorFlow >= 2.15:

``` python
import tensorflow as tf
print(tf.__version__)


import numpy as np
import mrmustard.lab_dev as mrml
from mrmustard import math
from mrmustard.training import Optimizer
math.change_backend('tensorflow')

S = mrml.SqueezedVacuum([0], r=1.0, phi=0, r_trainable=True, phi_trainable=True)

# made up, means nothing
def cost():
    ket = S.fock(shape=[3])
    return - math.real(ket[2])

circuit = mrml.Circuit([S])

# we used to do this:
opt = Optimizer()
opt.minimize(cost, by_optimizing=[circuit], max_steps=20)
```

``` console
ValueError: custom_gradient function expected to return 4 gradients, but returned 3 instead.
```
This issue arises in custom operations where a gradient function is
manually defined, and the expected number of gradients doesn't match the
number returned by the function. To fix this issue, we updated all
`custom_gradient` use cases in MM to return correct number of gradients.
:heavy_check_mark:

Python formatting could also be improved with supporting different
python version targets in `black` (to avoid formatting inconsistencies
when using different py versions) and sorting imports using `isort`.


___

### **PR Type**
enhancement, tests


___

### **Description**
- Updated TensorFlow version to 2.17.0 in `pyproject.toml` to ensure
compatibility with the latest features and improvements.
- Enhanced the `Makefile` to include `isort` for sorting imports and
added conditional checks for formatting.
- Modified the gradient function in `backend_tensorflow.py` to return an
additional `None` value, likely for improved error handling or
compatibility.
- Reformatted import statements across multiple test files for
consistency and readability.
- Added `isort` as a dependency and configured it alongside `black` for
code formatting.


[sc-75755]
___



### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant
files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
<summary><strong>backend_tensorflow.py</strong><dd><code>Update gradient
function to return extra None value</code>&nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; </dd></summary>
<hr>

mrmustard/math/backend_tensorflow.py

- Modified the `grad` function to return an additional `None` value.



</details>


  </td>
<td><a
href="https://github.com/XanaduAI/MrMustard/pull/506/files#diff-9b9d2f0045f871a5f865532687c4b9733e960270cfdb405a5688c2e62568feb0">+1/-1</a>&nbsp;
&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
  <td>
    <details>
<summary><strong>pyproject.toml</strong><dd><code>Update TensorFlow
version and add isort configuration</code>&nbsp; &nbsp; &nbsp; &nbsp;
</dd></summary>
<hr>

pyproject.toml

<li>Updated TensorFlow version to 2.17.0.<br> <li> Added
<code>isort</code> as a dependency.<br> <li> Configured
<code>isort</code> and <code>black</code> settings.<br>


</details>


  </td>
<td><a
href="https://github.com/XanaduAI/MrMustard/pull/506/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711">+11/-6</a>&nbsp;
&nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Configuration
changes</strong></td><td><table>
<tr>
  <td>
    <details>
<summary><strong>Makefile</strong><dd><code>Enhance Makefile with isort
and conditional formatting</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

Makefile

<li>Added <code>isort</code> to the format command.<br> <li> Introduced
conditional checks for formatting.<br>


</details>


  </td>
<td><a
href="https://github.com/XanaduAI/MrMustard/pull/506/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52">+11/-2</a>&nbsp;
&nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
<summary><strong>conftest.py</strong><dd><code>Add hypothesis settings
import</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
</dd></summary>
<hr>

tests/conftest.py

- Added import for `hypothesis.settings`.



</details>


  </td>
<td><a
href="https://github.com/XanaduAI/MrMustard/pull/506/files#diff-e52e4ddd58b7ef887ab03c04116e676f6280b824ab7469d5d3080e5cba4f2128">+3/-1</a>&nbsp;
&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Formatting</strong></td><td><table>
<tr>
  <td>
    <details>
<summary><strong>test_circuit.py</strong><dd><code>Reformat import
statements for consistency</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
</dd></summary>
<hr>

tests/test_lab/test_circuit.py

- Reformatted import statements for consistency.



</details>


  </td>
<td><a
href="https://github.com/XanaduAI/MrMustard/pull/506/files#diff-da6160d8a83f4a60dd97f6265f4578698d690235c644369d2b1b53da0fc27363">+1/-8</a>&nbsp;
&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull
request to receive relevant information

---------

Co-authored-by: Filippo Miatto <ziofil@users.noreply.github.com>
Co-authored-by: Filippo Miatto <miatto@gmail.com>